name: Website Monitor — Twilio Test

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "call | sms | both"
        required: true
        default: "both"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install twilio
      - name: Run Twilio test
        run: |
          if [ "${{ github.event.inputs.mode }}" = "call" ]; then
            python monitor.py --call
          elif [ "${{ github.event.inputs.mode }}" = "sms" ]; then
            python monitor.py --sms
          else
            python monitor.py --call
            python monitor.py --sms
          fi
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH: ${{ secrets.TWILIO_AUTH }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          TWILIO_TO: ${{ secrets.TWILIO_TO }}
