name: Website Monitor — Test Harness

on:
  workflow_dispatch:
    inputs:
      scenario:
        description: "call-test | probe | simulate-change | simulate-nochange | daily"
        required: true
        default: "probe"
      before_value:
        description: "seed value (simulate*)"
        required: false
        default: "November"
      after_value:
        description: "injected value (simulate-change)"
        required: false
        default: "December"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 twilio
      - run: mkdir -p state logs
      - name: Run scenario
        run: |
          SCEN="${{ github.event.inputs.scenario }}"
          case "$SCEN" in
            call-test)
              python monitor.py --test-call
              ;;
            probe)
              python monitor.py --probe
              ;;
            simulate-change)
              python monitor.py --set-state "${{ github.event.inputs.before_value }}"
              python monitor.py --check --inject-value "${{ github.event.inputs.after_value }}"
              ;;
            simulate-nochange)
              python monitor.py --set-state "${{ github.event.inputs.before_value }}"
              python monitor.py --check --inject-value "${{ github.event.inputs.before_value }}"
              ;;
            daily)
              python monitor.py --daily-summary --force-summary
              ;;
            *)
              echo "Unknown scenario"; exit 1
              ;;
          esac
        env:
          MONITOR_URL: ${{ secrets.MONITOR_URL }}
          MONITOR_CSS_SELECTOR: ${{ secrets.MONITOR_CSS_SELECTOR }}
          MONITOR_REGEX_CAPTURE: ${{ secrets.MONITOR_REGEX_CAPTURE }}
          MONITOR_STATE_FILE: "state/monitor_state.json"
          MONITOR_LOG_DIR: "logs"
          MONITOR_CALL_ON_ERROR: "1"   # optional: call on probe/extract errors
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH: ${{ secrets.TWILIO_AUTH }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          TWILIO_TO: ${{ secrets.TWILIO_TO }}

      - uses: actions/upload-artifact@v4
        with:
          name: monitor-logs
          path: logs/**
          if-no-files-found: ignore
