name: Website Monitor (live)

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 min checks
    - cron: "0 14 * * *"     # daily summary at 06:00 PST (UTC-8)
  workflow_dispatch:
    inputs:
      mode:
        description: "check | daily | seed-baseline"
        required: false
        default: "check"

permissions:
  contents: write   # commit state back to repo

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 twilio
      - name: Prepare folders
        run: mkdir -p state logs

      - name: Decide command
        id: which
        run: |
          if [ "${{ github.event_name }}" = "schedule" ] && [ "${{ github.event.schedule }}" = "0 20 * * *" ]; then
            echo "cmd=--daily-summary" >> $GITHUB_OUTPUT
          else
            MODE="${{ github.event.inputs.mode }}"
            if [ "$MODE" = "daily" ]; then
              echo "cmd=--daily-summary" >> $GITHUB_OUTPUT
            elif [ "$MODE" = "seed-baseline" ]; then
              echo "cmd=seed" >> $GITHUB_OUTPUT
            else
              echo "cmd=--check" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Run monitor
        run: |
          if [ "${{ steps.which.outputs.cmd }}" = "seed" ]; then
            python monitor.py --probe
            VAL="$(tail -n 50 logs/monitor.log | grep '\[PROBE\] Extracted value:' | tail -n 1 | sed 's/.*: //')"
            echo "Seeding baseline with: $VAL"
            python monitor.py --set-state "$VAL"
            python monitor.py --check --inject-value "$VAL"
          else
            python monitor.py ${{ steps.which.outputs.cmd }}
          fi
        env:
          MONITOR_URL: ${{ secrets.MONITOR_URL }}
          MONITOR_CSS_SELECTOR: ${{ secrets.MONITOR_CSS_SELECTOR }}
          MONITOR_REGEX_CAPTURE: ${{ secrets.MONITOR_REGEX_CAPTURE }}
          MONITOR_CSS_INDEX: ${{ secrets.MONITOR_CSS_INDEX }}
          MONITOR_STATE_FILE: "state/monitor_state.json"
          MONITOR_LOG_DIR: "logs"
          MONITOR_CALL_ON_ERROR: "1"
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH: ${{ secrets.TWILIO_AUTH }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          TWILIO_TO: ${{ secrets.TWILIO_TO }}

      - name: Commit updated state (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain state/monitor_state.json)" ]; then
            git add state/monitor_state.json logs/monitor.log || true
            git commit -m "chore: update monitor state [skip ci]" || echo "No changes to commit"
            git push
          else
            echo "State unchanged; nothing to commit."
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/**
          if-no-files-found: ignore
